package MsgLang.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import java.util.Map;
import org.jetbrains.mps.openapi.language.SProperty;
import jetbrains.mps.smodel.runtime.PropertyConstraintsDescriptor;
import java.util.HashMap;
import jetbrains.mps.smodel.runtime.base.BasePropertyConstraintsDescriptor;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;

public class MessageStructure_Constraints extends BaseConstraintsDescriptor {
  public MessageStructure_Constraints() {
    super(MetaAdapterFactory.getConcept(0x4575325384d849a8L, 0x8c745ee559257f87L, 0x7959d2386a4ad6b1L, "MsgLang.structure.MessageStructure"));
  }

  @Override
  protected Map<SProperty, PropertyConstraintsDescriptor> getSpecifiedProperties() {
    Map<SProperty, PropertyConstraintsDescriptor> properties = new HashMap<SProperty, PropertyConstraintsDescriptor>();
    properties.put(MetaAdapterFactory.getProperty(0x4575325384d849a8L, 0x8c745ee559257f87L, 0x7959d2386a4ad6b1L, 0x7959d2386a4ad6c0L, "MinLength"), new BasePropertyConstraintsDescriptor(MetaIdFactory.propId(0x4575325384d849a8L, 0x8c745ee559257f87L, 0x7959d2386a4ad6b1L, 0x7959d2386a4ad6c0L), this) {
      @Override
      public boolean hasOwnValidator() {
        return true;
      }
      @Override
      public boolean validateValue(SNode node, String propertyValue) {
        String propertyName = "MinLength";
        return (SPropertyOperations.getInteger(propertyValue)) > 0;
      }
    });
    properties.put(MetaAdapterFactory.getProperty(0x4575325384d849a8L, 0x8c745ee559257f87L, 0x7959d2386a4ad6b1L, 0x86c58d7abffddb7L, "MaxLength"), new BasePropertyConstraintsDescriptor(MetaIdFactory.propId(0x4575325384d849a8L, 0x8c745ee559257f87L, 0x7959d2386a4ad6b1L, 0x86c58d7abffddb7L), this) {
      @Override
      public boolean hasOwnValidator() {
        return true;
      }
      @Override
      public boolean validateValue(SNode node, String propertyValue) {
        String propertyName = "MaxLength";
        return (SPropertyOperations.getInteger(propertyValue)) > SPropertyOperations.getInteger(node, MetaAdapterFactory.getProperty(0x4575325384d849a8L, 0x8c745ee559257f87L, 0x7959d2386a4ad6b1L, 0x7959d2386a4ad6c0L, "MinLength")) || (SPropertyOperations.getInteger(propertyValue)) == 0;
      }
    });
    return properties;
  }
}
