package MsgLang.structure;

/*Generated by MPS */

import java.util.List;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import java.util.LinkedList;

public enum FormatEnum {
  V("V", "Value"),
  TLV("TLV", "TagLenghtValue");

  private final String myName;
  public String getName() {
    return myName;
  }
  private final String myValue;
  private FormatEnum(String name, String value) {
    myName = name;
    myValue = value;
  }
  public String getValue() {
    return myValue;
  }
  public String getValueAsString() {
    return myValue;
  }
  public static List<FormatEnum> getConstants() {
    List<FormatEnum> list = ListSequence.fromList(new LinkedList<FormatEnum>());
    ListSequence.fromList(list).addElement(FormatEnum.V);
    ListSequence.fromList(list).addElement(FormatEnum.TLV);
    return list;
  }
  public static FormatEnum getDefault() {
    return null;
  }
  public static FormatEnum parseValue(String value) {
    if (value == null) {
      return FormatEnum.getDefault();
    }
    if (value.equals(FormatEnum.V.getValueAsString())) {
      return FormatEnum.V;
    }
    if (value.equals(FormatEnum.TLV.getValueAsString())) {
      return FormatEnum.TLV;
    }
    return FormatEnum.getDefault();
  }
}
