package MsgLang.structure;

/*Generated by MPS */

import java.util.List;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import java.util.LinkedList;

public enum PresenceEnum {
  M("Mandatory", "M"),
  O("Optional", "O"),
  C("Conditional", "C");

  private final String myName;
  public String getName() {
    return myName;
  }
  private final String myValue;
  private PresenceEnum(String name, String value) {
    myName = name;
    myValue = value;
  }
  public String getValue() {
    return myValue;
  }
  public String getValueAsString() {
    return myValue;
  }
  public static List<PresenceEnum> getConstants() {
    List<PresenceEnum> list = ListSequence.fromList(new LinkedList<PresenceEnum>());
    ListSequence.fromList(list).addElement(PresenceEnum.M);
    ListSequence.fromList(list).addElement(PresenceEnum.O);
    ListSequence.fromList(list).addElement(PresenceEnum.C);
    return list;
  }
  public static PresenceEnum getDefault() {
    return null;
  }
  public static PresenceEnum parseValue(String value) {
    if (value == null) {
      return PresenceEnum.getDefault();
    }
    if (value.equals(PresenceEnum.M.getValueAsString())) {
      return PresenceEnum.M;
    }
    if (value.equals(PresenceEnum.O.getValueAsString())) {
      return PresenceEnum.O;
    }
    if (value.equals(PresenceEnum.C.getValueAsString())) {
      return PresenceEnum.C;
    }
    return PresenceEnum.getDefault();
  }
}
