package MsgLang.structure;

/*Generated by MPS */

import java.util.List;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import java.util.LinkedList;

public enum PresenceEnum {
  Mandatory("M", "Mandatory"),
  Optional("O", "Optional"),
  Conditional("C", "Conditional");

  private final String myName;
  public String getName() {
    return myName;
  }
  private final String myValue;
  private PresenceEnum(String name, String value) {
    myName = name;
    myValue = value;
  }
  public String getValue() {
    return myValue;
  }
  public String getValueAsString() {
    return myValue;
  }
  public static List<PresenceEnum> getConstants() {
    List<PresenceEnum> list = ListSequence.fromList(new LinkedList<PresenceEnum>());
    ListSequence.fromList(list).addElement(PresenceEnum.Mandatory);
    ListSequence.fromList(list).addElement(PresenceEnum.Optional);
    ListSequence.fromList(list).addElement(PresenceEnum.Conditional);
    return list;
  }
  public static PresenceEnum getDefault() {
    return null;
  }
  public static PresenceEnum parseValue(String value) {
    if (value == null) {
      return PresenceEnum.getDefault();
    }
    if (value.equals(PresenceEnum.Mandatory.getValueAsString())) {
      return PresenceEnum.Mandatory;
    }
    if (value.equals(PresenceEnum.Optional.getValueAsString())) {
      return PresenceEnum.Optional;
    }
    if (value.equals(PresenceEnum.Conditional.getValueAsString())) {
      return PresenceEnum.Conditional;
    }
    return PresenceEnum.getDefault();
  }
}
